// Content (spec 6.3 content tables, 7.5 content router): campaigns, briefs, packages with immutable content
// revisions, channel variants and the calendar. The review and publishing modules read revisions and variants here.
export {
  contentService,
  hashesForVariant,
  contentClassOf,
  registerChannelResolver,
  resetChannelResolver,
  registerDestinationResolver,
  resetDestinationResolver,
  registerCalendarSource,
  registerRevisionChangeListener,
  registerLinkTracker,
  registerAttributeCapturer,
  registerVariantValidator,
  resetVariantValidator,
  type ChannelDescription,
  type ChannelResolver,
  type DestinationResolver,
  type DestinationDescription,
  type CalendarSource,
  type RevisionChange,
  type RevisionChangeListener,
  type LinkTracker,
  type LinkTrackingInput,
  type AttributeCapturer,
  type AttributeCaptureInput,
  type VariantValidator,
  type ContentRevisionDto,
  type ChannelVariantDto,
  type ContentActorOptions,
  type PlanItemDto,
} from './service';
export { contentToolSource } from './tools';
export {
  CampaignRepository,
  BriefRepository,
  ContentPackageRepository,
  ContentRevisionRepository,
  ChannelVariantRepository,
  CreativeAttributeRepository,
  PlanItemRepository,
} from './repositories';
