import { getTableName } from 'drizzle-orm';
import { MySqlTable } from 'drizzle-orm/mysql-core';
import mysql from 'mysql2/promise';
import * as schema from './schema';
import { INSERT_ONLY_TABLES, RETENTION_ROLE_GRANTS } from './global-tables';

/**
 * Spec 6.1 immutability: the application DB role has no UPDATE/DELETE on insert-only tables. The SQL is generated
 * from the schema and INSERT_ONLY_TABLES so the grant list cannot drift (tooling/scripts/generate-db-roles.ts).
 */
const schemaTables = (): string[] =>
  (Object.values(schema) as unknown[])
    .filter((v): v is MySqlTable => v instanceof MySqlTable)
    .map((t) => getTableName(t))
    .sort();

export function generateRoleSql(dbName: string, user: string, host = '%'): string {
  const tables = schemaTables();
  const insertOnly = new Set(INSERT_ONLY_TABLES);
  const lines: string[] = [
    '-- Generated by tooling/scripts/generate-db-roles.ts. Do not edit by hand.',
    '-- Application role for Oremedia: full DML on mutable tables, INSERT/SELECT only on insert-only evidence tables (spec 6.1).',
    `CREATE USER IF NOT EXISTS '${user}'@'${host}';`,
    `REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${user}'@'${host}';`,
  ];
  for (const t of tables) {
    if (insertOnly.has(t))
      lines.push(`GRANT SELECT, INSERT ON \`${dbName}\`.\`${t}\` TO '${user}'@'${host}';`);
    else lines.push(`GRANT SELECT, INSERT, UPDATE, DELETE ON \`${dbName}\`.\`${t}\` TO '${user}'@'${host}';`);
  }
  lines.push(
    `GRANT SELECT, INSERT, UPDATE ON \`${dbName}\`.\`__drizzle_migrations\` TO '${user}'@'${host}';`,
  );
  lines.push('FLUSH PRIVILEGES;');
  return lines.join('\n') + '\n';
}

/**
 * Spec 17.5: the retention role (roles/retention-role.sql), generated from RETENTION_ROLE_GRANTS so the grant list
 * cannot drift from the schema: a listed table that does not exist fails generation. No migrations table, no
 * DDL, nothing beyond the listed privileges.
 */
export function generateRetentionRoleSql(dbName: string, user: string, host = '%'): string {
  const tables = new Set(schemaTables());
  const lines: string[] = [
    '-- Generated by tooling/scripts/generate-db-roles.ts. Do not edit by hand.',
    '-- Retention role for Oremedia: used only by retentionSweepWorkflowV1 activities (DATABASE_URL_RETENTION, spec 17.5).',
    `CREATE USER IF NOT EXISTS '${user}'@'${host}';`,
    `REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${user}'@'${host}';`,
  ];
  for (const [t, privileges] of Object.entries(RETENTION_ROLE_GRANTS).sort(([a], [b]) =>
    a.localeCompare(b),
  )) {
    if (!tables.has(t)) throw new Error(`RETENTION_ROLE_GRANTS lists ${t}, which is not in the schema`);
    lines.push(`GRANT ${privileges.join(', ')} ON \`${dbName}\`.\`${t}\` TO '${user}'@'${host}';`);
  }
  lines.push('FLUSH PRIVILEGES;');
  return lines.join('\n') + '\n';
}

/**
 * R1-G (D-25): what a connection URL's user actually holds, read with `SELECT CURRENT_USER()` and `SHOW GRANTS`
 * only (the roles granted to the user are expanded with `USING`, so a privilege held through a role is seen).
 * Used by `pnpm db:roles:check` (tooling/scripts/db-roles); never logs the URL.
 */
export async function readHeldGrants(url: string): Promise<{ user: string; grants: string[] }> {
  const conn = await mysql.createConnection({ uri: url });
  try {
    const [who] = await conn.query<mysql.RowDataPacket[]>('SELECT CURRENT_USER() AS u, CURRENT_ROLE() AS r');
    const roles = String(who[0]?.['r'] ?? 'NONE');
    const using = roles === 'NONE' ? '' : ` USING ${roles}`;
    const [rows] = await conn.query<mysql.RowDataPacket[]>(`SHOW GRANTS FOR CURRENT_USER()${using}`);
    return { user: String(who[0]?.['u'] ?? ''), grants: rows.map((r) => String(Object.values(r)[0] ?? '')) };
  } finally {
    await conn.end();
  }
}
