import { getTableName } from 'drizzle-orm';
import { MySqlTable } from 'drizzle-orm/mysql-core';
import mysql from 'mysql2/promise';
import * as schema from './schema';
import { DELETION_ROLE_DELETES, INSERT_ONLY_TABLES, RETENTION_ROLE_GRANTS } from './global-tables';

import { compareGrants, formatDiff, grantSetOf, parseGrant, userOf } from './roles-compare';

export { compareGrants, formatDiff, grantSetOf, parseGrant, userOf };
export type { GrantDiff, GrantSet } from './roles-compare';

/**
 * Spec 6.1 immutability: the application DB role has no UPDATE/DELETE on insert-only tables. The SQL is generated
 * from the schema and INSERT_ONLY_TABLES so the grant list cannot drift (tooling/scripts/generate-db-roles.ts).
 */
const schemaTables = (): string[] =>
  (Object.values(schema) as unknown[])
    .filter((v): v is MySqlTable => v instanceof MySqlTable)
    .map((t) => getTableName(t))
    .sort();

export function generateRoleSql(dbName: string, user: string, host = '%'): string {
  const tables = schemaTables();
  const insertOnly = new Set(INSERT_ONLY_TABLES);
  const lines: string[] = [
    '-- Generated by tooling/scripts/generate-db-roles.ts. Do not edit by hand.',
    '-- Application role for Oremedia: full DML on mutable tables, INSERT/SELECT only on insert-only evidence tables (spec 6.1).',
    `CREATE USER IF NOT EXISTS '${user}'@'${host}';`,
    `REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${user}'@'${host}';`,
  ];
  for (const t of tables) {
    if (insertOnly.has(t))
      lines.push(`GRANT SELECT, INSERT ON \`${dbName}\`.\`${t}\` TO '${user}'@'${host}';`);
    else lines.push(`GRANT SELECT, INSERT, UPDATE, DELETE ON \`${dbName}\`.\`${t}\` TO '${user}'@'${host}';`);
  }
  lines.push(
    `GRANT SELECT, INSERT, UPDATE ON \`${dbName}\`.\`__drizzle_migrations\` TO '${user}'@'${host}';`,
  );
  lines.push('FLUSH PRIVILEGES;');
  return lines.join('\n') + '\n';
}

/**
 * Spec 17.5: the retention role (roles/retention-role.sql), generated from RETENTION_ROLE_GRANTS so the grant list
 * cannot drift from the schema: a listed table that does not exist fails generation. No migrations table, no
 * DDL, nothing beyond the listed privileges.
 */
export function generateRetentionRoleSql(dbName: string, user: string, host = '%'): string {
  const tables = new Set(schemaTables());
  const lines: string[] = [
    '-- Generated by tooling/scripts/generate-db-roles.ts. Do not edit by hand.',
    '-- Retention role for Oremedia: used only by retentionSweepWorkflowV1 activities (DATABASE_URL_RETENTION, spec 17.5).',
    `CREATE USER IF NOT EXISTS '${user}'@'${host}';`,
    `REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${user}'@'${host}';`,
  ];
  for (const [t, privileges] of Object.entries(RETENTION_ROLE_GRANTS).sort(([a], [b]) =>
    a.localeCompare(b),
  )) {
    if (!tables.has(t)) throw new Error(`RETENTION_ROLE_GRANTS lists ${t}, which is not in the schema`);
    lines.push(`GRANT ${privileges.join(', ')} ON \`${dbName}\`.\`${t}\` TO '${user}'@'${host}';`);
  }
  lines.push('FLUSH PRIVILEGES;');
  return lines.join('\n') + '\n';
}

/**
 * Spec 17.5 / 6.1: the deletion role (roles/deletion-role.sql): the application role's grants on every table, plus
 * DELETE on the insert-only tables a tenant or brand deletion removes (DELETION_ROLE_DELETES), and nothing else: no
 * UPDATE on an insert-only table, no DELETE on audit_events or remote_evidence, no migrations table, no DDL. A
 * listed table that is not insert-only or not in the schema fails generation.
 */
export function generateDeletionRoleSql(dbName: string, user: string, host = '%'): string {
  const tables = schemaTables();
  const insertOnly = new Set(INSERT_ONLY_TABLES);
  const deletes = new Set(DELETION_ROLE_DELETES);
  for (const t of deletes) {
    if (!tables.includes(t)) throw new Error(`DELETION_ROLE_DELETES lists ${t}, which is not in the schema`);
    if (!insertOnly.has(t)) throw new Error(`DELETION_ROLE_DELETES lists ${t}, which is not insert-only`);
  }
  const lines: string[] = [
    '-- Generated by tooling/scripts/generate-db-roles.ts. Do not edit by hand.',
    '-- Deletion role for Oremedia: used only by deletionRequestWorkflowV1 handler steps (DATABASE_URL_DELETION, spec 17.5).',
    `CREATE USER IF NOT EXISTS '${user}'@'${host}';`,
    `REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${user}'@'${host}';`,
  ];
  for (const t of tables) {
    if (deletes.has(t))
      lines.push(`GRANT SELECT, INSERT, DELETE ON \`${dbName}\`.\`${t}\` TO '${user}'@'${host}';`);
    else if (insertOnly.has(t))
      lines.push(`GRANT SELECT, INSERT ON \`${dbName}\`.\`${t}\` TO '${user}'@'${host}';`);
    else lines.push(`GRANT SELECT, INSERT, UPDATE, DELETE ON \`${dbName}\`.\`${t}\` TO '${user}'@'${host}';`);
  }
  lines.push('FLUSH PRIVILEGES;');
  return lines.join('\n') + '\n';
}

/**
 * R1-G (D-25): what a connection URL's user actually holds, read with `SELECT CURRENT_USER()` and `SHOW GRANTS`
 * only (the roles granted to the user are expanded with `USING`, so a privilege held through a role is seen).
 * Used by `pnpm db:roles:check` (tooling/scripts/db-roles); never logs the URL.
 */
export async function readHeldGrants(url: string): Promise<{ user: string; grants: string[] }> {
  const conn = await mysql.createConnection({ uri: url });
  try {
    const [who] = await conn.query<mysql.RowDataPacket[]>('SELECT CURRENT_USER() AS u, CURRENT_ROLE() AS r');
    const roles = String(who[0]?.['r'] ?? 'NONE');
    const using = roles === 'NONE' ? '' : ` USING ${roles}`;
    const [rows] = await conn.query<mysql.RowDataPacket[]>(`SHOW GRANTS FOR CURRENT_USER()${using}`);
    return { user: String(who[0]?.['u'] ?? ''), grants: rows.map((r) => String(Object.values(r)[0] ?? '')) };
  } finally {
    await conn.end();
  }
}

const sleep = (ms: number): Promise<void> => new Promise((resolve) => setTimeout(resolve, ms));

/** The tables the generated role SQL grants on, in the database it names. */
const tablesNamedBy = (statements: readonly string[], database: string): string[] =>
  statements
    .map((s) => parseGrant(s)?.target ?? '')
    .filter((t) => t.startsWith(`${database}.`))
    .map((t) => t.slice(database.length + 1));

/**
 * R1-G (D-25): applies a generated role to the database `adminUrl` names, as the admin that URL connects as, and
 * returns the same lines `pnpm db:roles:check` prints for it (`formatDiff`). The user is created when missing, its
 * password set, every privilege revoked and the role's grants re-applied, so a re-run after a migration brings
 * the grants up to date. Before touching the user it waits (up to `waitForTablesMs`, default ten minutes) for every
 * table the role names to exist, so a redeploy that races the api's migration never leaves a table without its
 * grant and never revokes the running user's privileges while a table is still missing. Logs and returns no
 * password and no URL.
 */
export async function applyRoleSql(
  adminUrl: string,
  role: string,
  user: string,
  password: string,
  sqlFor: (dbName: string, user: string) => string,
  waitForTablesMs = 10 * 60_000,
): Promise<string[]> {
  const { database } = userOf(adminUrl);
  const statements = sqlFor(database, user).split('\n');
  const admin = await mysql.createConnection({ uri: adminUrl });
  try {
    const deadline = Date.now() + waitForTablesMs;
    for (;;) {
      const [rows] = await admin.query<mysql.RowDataPacket[]>(
        'SELECT table_name AS t FROM information_schema.tables WHERE table_schema = ?',
        [database],
      );
      const present = new Set(rows.map((r) => String(r['t'])));
      const missing = tablesNamedBy(statements, database).filter((t) => !present.has(t));
      if (!missing.length) break;
      if (Date.now() >= deadline)
        throw new Error(`${role}: tables the role names do not exist yet: ${missing.join(', ')}`);
      await sleep(15_000);
    }
    for (const statement of statements) {
      const text = statement.trim();
      if (!text || text.startsWith('--')) continue;
      await admin.query(text);
    }
    await admin.query(`ALTER USER ${admin.escape(user)}@'%' IDENTIFIED BY ${admin.escape(password)}`);
  } finally {
    await admin.end();
  }
  const asRole = new URL(adminUrl);
  asRole.username = encodeURIComponent(user);
  asRole.password = encodeURIComponent(password);
  const held = await readHeldGrants(asRole.toString());
  const diff = compareGrants(grantSetOf(statements, database), grantSetOf(held.grants, database));
  return [`${role}: applied to ${held.user} on ${database}`, ...formatDiff(role, user, diff)];
}
