import type { ElementSpec, LogoSpec, StarterSpec } from './index';

/**
 * The built-in starters (STU-1a). Boxes are in page pixels of the starter's format and stay inside its safe area
 * (decoration may bleed); every text box is generous for its sample copy and shrinks to fit longer copy. Hierarchy:
 * one display or heading line, supporting body, one call to action, the logo in a corner clear of everything else.
 */

const SQUARE = ['instagram_business', 'facebook_page', 'linkedin_page'] as const;
const PORTRAIT = ['instagram_business'] as const;
const STORY = ['instagram_business', 'facebook_page', 'tiktok'] as const;

const logo = (corner: LogoSpec['corner'], width = 200): LogoSpec => ({ kind: 'logo', corner, width });

/** A pill button: a rounded rect and its label centred on it. */
const button = (
  x: number,
  y: number,
  width: number,
  height: number,
  label: string,
  fill: 'accent' | 'light',
  sizePx = 32,
): ElementSpec[] => [
  { kind: 'shape', name: 'Button', shape: 'rect', fill, box: [x, y, width, height], radius: height / 2 },
  {
    kind: 'text',
    name: 'Call to action',
    role: 'cta',
    text: label,
    typeRole: 'label',
    sizePx,
    align: 'center',
    box: [x, y + Math.round((height - sizePx * 1.2) / 2), width, Math.round(sizePx * 1.25)],
    on: fill,
    maxLength: 24,
  },
];

export const STARTER_SPECS: readonly StarterSpec[] = [
  {
    key: 'post-bold-headline',
    name: 'Bold headline',
    description: 'A promotional post that leads with one strong line and a clear call to action.',
    contentType: 'social_post',
    formatKey: 'square_1080',
    channels: SQUARE,
    pages: [
      {
        name: 'Post',
        ground: 'light',
        elements: [
          {
            kind: 'shape',
            name: 'Accent bar',
            shape: 'rect',
            fill: 'accent',
            box: [0, 0, 1080, 20],
            role: 'decoration',
          },
          {
            kind: 'text',
            name: 'Eyebrow',
            text: 'NEW THIS SEASON',
            typeRole: 'label',
            sizePx: 26,
            tracking: 0.08,
            box: [96, 110, 700, 40],
            on: 'light',
            tint: 'accent',
          },
          {
            kind: 'text',
            name: 'Headline',
            role: 'headline',
            text: 'Say the big thing in a few words',
            typeRole: 'display',
            sizePx: 92,
            box: [96, 170, 888, 340],
            on: 'light',
            maxLength: 60,
          },
          {
            kind: 'text',
            name: 'Body',
            role: 'body',
            text: 'One or two lines on what it is and why it matters to the reader.',
            typeRole: 'body',
            sizePx: 32,
            lineHeight: 1.35,
            box: [96, 530, 760, 140],
            on: 'light',
            maxLength: 160,
          },
          ...button(96, 744, 380, 96, 'Find out more', 'accent'),
          logo('bottom-right'),
        ],
      },
    ],
  },
  {
    key: 'post-photo-feature',
    name: 'Photo feature',
    description: 'A post built around one photograph, with a headline and a line of detail underneath.',
    contentType: 'social_post',
    formatKey: 'square_1080',
    channels: SQUARE,
    pages: [
      {
        name: 'Post',
        ground: 'light',
        elements: [
          { kind: 'imageArea', name: 'Image area', box: [54, 54, 972, 560] },
          {
            kind: 'text',
            name: 'Headline',
            role: 'headline',
            text: 'A headline that names the benefit',
            typeRole: 'heading',
            sizePx: 64,
            box: [96, 650, 888, 170],
            on: 'light',
            maxLength: 60,
          },
          {
            kind: 'text',
            name: 'Body',
            role: 'body',
            text: 'A short line of supporting detail.',
            typeRole: 'body',
            sizePx: 30,
            lineHeight: 1.35,
            box: [96, 830, 600, 100],
            on: 'light',
            maxLength: 120,
          },
          logo('bottom-right', 180),
        ],
      },
    ],
  },
  {
    key: 'post-offer',
    name: 'Offer on dark',
    description: 'A limited-time offer on the brand’s dark colour, with a contrasting button.',
    contentType: 'social_post',
    formatKey: 'square_1080',
    channels: SQUARE,
    pages: [
      {
        name: 'Post',
        ground: 'dark',
        elements: [
          {
            kind: 'shape',
            name: 'Accent circle',
            shape: 'ellipse',
            fill: 'accent',
            box: [760, -200, 520, 520],
            role: 'decoration',
          },
          {
            kind: 'text',
            name: 'Eyebrow',
            text: 'LIMITED TIME',
            typeRole: 'label',
            sizePx: 28,
            tracking: 0.08,
            box: [96, 130, 600, 44],
            on: 'dark',
            tint: 'accent',
          },
          {
            kind: 'text',
            name: 'Headline',
            role: 'headline',
            text: 'Your offer, in bold',
            typeRole: 'display',
            sizePx: 120,
            lineHeight: 1.05,
            box: [96, 380, 888, 300],
            on: 'dark',
            maxLength: 40,
          },
          {
            kind: 'text',
            name: 'Body',
            role: 'body',
            text: 'Say what it includes and until when.',
            typeRole: 'body',
            sizePx: 34,
            lineHeight: 1.35,
            box: [96, 700, 700, 110],
            on: 'dark',
            maxLength: 120,
          },
          ...button(96, 850, 360, 96, 'Shop now', 'light'),
          logo('bottom-right', 180),
        ],
      },
    ],
  },
  {
    key: 'portrait-quote',
    name: 'Customer quote',
    description: 'A testimonial in the taller feed format: the quote, who said it, and the logo.',
    contentType: 'social_post',
    formatKey: 'ig_feed_4x5',
    channels: PORTRAIT,
    pages: [
      {
        name: 'Post',
        ground: 'light',
        elements: [
          {
            kind: 'text',
            name: 'Quote mark',
            role: 'decoration',
            text: '“',
            typeRole: 'display',
            sizePx: 240,
            lineHeight: 1,
            box: [96, 110, 200, 240],
            on: 'light',
            tint: 'accent',
          },
          {
            kind: 'text',
            name: 'Quote',
            role: 'headline',
            text: 'Put a short customer quote here, in their own words.',
            typeRole: 'heading',
            sizePx: 64,
            lineHeight: 1.25,
            box: [96, 360, 888, 470],
            on: 'light',
            maxLength: 140,
          },
          {
            kind: 'shape',
            name: 'Rule',
            shape: 'rect',
            fill: 'accent',
            box: [96, 860, 120, 6],
            role: 'decoration',
          },
          {
            kind: 'text',
            name: 'Attribution',
            role: 'body',
            text: 'Name, role at company',
            typeRole: 'body',
            sizePx: 30,
            box: [96, 890, 700, 80],
            on: 'light',
            maxLength: 80,
          },
          logo('bottom-left'),
        ],
      },
    ],
  },
  {
    key: 'portrait-product',
    name: 'Product spotlight',
    description: 'One product with its price, a headline and a buy button, in the taller feed format.',
    contentType: 'social_post',
    formatKey: 'ig_feed_4x5',
    channels: PORTRAIT,
    pages: [
      {
        name: 'Post',
        ground: 'light',
        elements: [
          { kind: 'imageArea', name: 'Image area', box: [54, 54, 972, 700] },
          {
            kind: 'text',
            name: 'Price',
            role: 'price',
            text: '€49',
            typeRole: 'heading',
            sizePx: 56,
            box: [96, 790, 400, 80],
            on: 'light',
            tint: 'accent',
            maxLength: 20,
          },
          {
            kind: 'text',
            name: 'Headline',
            role: 'headline',
            text: 'Name the product and its best feature',
            typeRole: 'heading',
            sizePx: 60,
            box: [96, 880, 888, 160],
            on: 'light',
            maxLength: 60,
          },
          {
            kind: 'text',
            name: 'Body',
            role: 'body',
            text: 'One line of detail.',
            typeRole: 'body',
            sizePx: 30,
            box: [96, 1050, 620, 90],
            on: 'light',
            maxLength: 100,
          },
          ...button(96, 1170, 320, 88, 'Buy now', 'accent', 30),
          logo('bottom-right', 180),
        ],
      },
    ],
  },
  {
    key: 'carousel-3-steps',
    name: 'Three-step guide',
    description: 'A short carousel: a cover, two steps and a closing call to action.',
    contentType: 'carousel',
    formatKey: 'square_1080',
    channels: SQUARE,
    pages: [
      {
        name: 'Cover',
        ground: 'dark',
        elements: [
          {
            kind: 'text',
            name: 'Eyebrow',
            text: 'A QUICK GUIDE',
            typeRole: 'label',
            sizePx: 28,
            tracking: 0.08,
            box: [96, 300, 700, 44],
            on: 'dark',
            tint: 'accent',
          },
          {
            kind: 'text',
            name: 'Headline',
            role: 'headline',
            text: 'Three steps to a better result',
            typeRole: 'display',
            sizePx: 96,
            box: [96, 360, 888, 320],
            on: 'dark',
            maxLength: 60,
          },
          {
            kind: 'text',
            name: 'Swipe hint',
            role: 'body',
            text: 'Swipe to start →',
            typeRole: 'body',
            sizePx: 30,
            box: [96, 720, 600, 60],
            on: 'dark',
          },
          logo('bottom-right', 180),
        ],
      },
      {
        name: 'Steps',
        ground: 'light',
        elements: [
          {
            kind: 'text',
            name: 'Step 1 label',
            text: 'STEP 1',
            typeRole: 'label',
            sizePx: 26,
            tracking: 0.08,
            box: [96, 110, 400, 44],
            on: 'light',
            tint: 'accent',
          },
          {
            kind: 'text',
            name: 'Step 1',
            role: 'headline',
            text: 'Do the first thing',
            typeRole: 'heading',
            sizePx: 64,
            box: [96, 170, 888, 170],
            on: 'light',
            maxLength: 50,
          },
          {
            kind: 'text',
            name: 'Step 1 detail',
            role: 'body',
            text: 'Explain the step in a sentence, with one concrete detail.',
            typeRole: 'body',
            sizePx: 30,
            lineHeight: 1.35,
            box: [96, 350, 888, 130],
            on: 'light',
            maxLength: 140,
          },
          {
            kind: 'text',
            name: 'Step 2 label',
            text: 'STEP 2',
            typeRole: 'label',
            sizePx: 26,
            tracking: 0.08,
            box: [96, 540, 400, 44],
            on: 'light',
            tint: 'accent',
          },
          {
            kind: 'text',
            name: 'Step 2',
            role: 'headline',
            text: 'Then the second',
            typeRole: 'heading',
            sizePx: 64,
            box: [96, 600, 888, 170],
            on: 'light',
            maxLength: 50,
          },
          {
            kind: 'text',
            name: 'Step 2 detail',
            role: 'body',
            text: 'Keep each step short enough to read at a glance.',
            typeRole: 'body',
            sizePx: 30,
            lineHeight: 1.35,
            box: [96, 780, 640, 110],
            on: 'light',
            maxLength: 140,
          },
          logo('bottom-right', 180),
        ],
      },
      {
        name: 'Call to action',
        ground: 'accent',
        elements: [
          {
            kind: 'text',
            name: 'Headline',
            role: 'headline',
            text: 'Ready to try it?',
            typeRole: 'display',
            sizePx: 96,
            box: [96, 300, 888, 300],
            on: 'accent',
            maxLength: 50,
          },
          {
            kind: 'text',
            name: 'Body',
            role: 'body',
            text: 'Tell people exactly what to do next.',
            typeRole: 'body',
            sizePx: 32,
            lineHeight: 1.35,
            box: [96, 620, 700, 100],
            on: 'accent',
            maxLength: 120,
          },
          ...button(96, 760, 380, 96, 'Get started', 'light'),
          logo('bottom-right', 180),
        ],
      },
    ],
  },
  {
    key: 'carousel-5-tips',
    name: 'Five-slide tips',
    description: 'A carousel of three tips between a cover and a closing slide, in the taller feed format.',
    contentType: 'carousel',
    formatKey: 'ig_feed_4x5',
    channels: PORTRAIT,
    pages: [
      {
        name: 'Cover',
        ground: 'dark',
        elements: [
          {
            kind: 'text',
            name: 'Eyebrow',
            text: '3 TIPS',
            typeRole: 'label',
            sizePx: 28,
            tracking: 0.08,
            box: [96, 400, 700, 44],
            on: 'dark',
            tint: 'accent',
          },
          {
            kind: 'text',
            name: 'Headline',
            role: 'headline',
            text: 'Tips your audience will save for later',
            typeRole: 'display',
            sizePx: 96,
            box: [96, 460, 888, 420],
            on: 'dark',
            maxLength: 60,
          },
          {
            kind: 'text',
            name: 'Swipe hint',
            role: 'body',
            text: 'Swipe →',
            typeRole: 'body',
            sizePx: 30,
            box: [96, 920, 400, 60],
            on: 'dark',
          },
          logo('bottom-right', 180),
        ],
      },
      ...[1, 2, 3].map((n) => ({
        name: `Tip ${n}`,
        ground: 'light' as const,
        elements: [
          {
            kind: 'text',
            name: 'Tip label',
            text: `TIP ${n}`,
            typeRole: 'label',
            sizePx: 26,
            tracking: 0.08,
            box: [96, 110, 400, 44],
            on: 'light',
            tint: 'accent',
          },
          {
            kind: 'text',
            name: 'Tip',
            role: 'headline',
            text: 'Write the tip as a short instruction',
            typeRole: 'heading',
            sizePx: 60,
            box: [96, 170, 888, 250],
            on: 'light',
            maxLength: 60,
          },
          {
            kind: 'text',
            name: 'Why it works',
            role: 'body',
            text: 'Add the why in one or two sentences so the tip sticks.',
            typeRole: 'body',
            sizePx: 32,
            lineHeight: 1.35,
            box: [96, 440, 888, 220],
            on: 'light',
            maxLength: 160,
          },
          { kind: 'imageArea', name: 'Image area', box: [96, 700, 888, 420], radius: 24 },
          logo('bottom-right', 180),
        ] satisfies ElementSpec[],
      })),
      {
        name: 'Call to action',
        ground: 'accent',
        elements: [
          {
            kind: 'text',
            name: 'Headline',
            role: 'headline',
            text: 'Save this for later',
            typeRole: 'display',
            sizePx: 96,
            box: [96, 400, 888, 320],
            on: 'accent',
            maxLength: 50,
          },
          {
            kind: 'text',
            name: 'Body',
            role: 'body',
            text: 'Follow for a new tip every week.',
            typeRole: 'body',
            sizePx: 32,
            lineHeight: 1.35,
            box: [96, 740, 760, 100],
            on: 'accent',
            maxLength: 120,
          },
          ...button(96, 880, 380, 96, 'Follow', 'light'),
          logo('bottom-right', 180),
        ],
      },
    ],
  },
  {
    key: 'story-announcement',
    name: 'Story announcement',
    description:
      'A vertical story that announces one thing, with the logo up top and a button above the reply bar.',
    contentType: 'story',
    formatKey: 'ig_story_9x16',
    channels: STORY,
    pages: [
      {
        name: 'Story',
        ground: 'dark',
        elements: [
          logo('top-left'),
          {
            kind: 'text',
            name: 'Eyebrow',
            text: 'ANNOUNCING',
            typeRole: 'label',
            sizePx: 30,
            tracking: 0.08,
            box: [96, 620, 800, 48],
            on: 'dark',
            tint: 'accent',
          },
          {
            kind: 'text',
            name: 'Headline',
            role: 'headline',
            text: 'Something new is here',
            typeRole: 'display',
            sizePx: 120,
            lineHeight: 1.05,
            box: [96, 690, 888, 520],
            on: 'dark',
            maxLength: 50,
          },
          {
            kind: 'text',
            name: 'Body',
            role: 'body',
            text: 'Give the one detail people need to care.',
            typeRole: 'body',
            sizePx: 36,
            lineHeight: 1.35,
            box: [96, 1230, 820, 160],
            on: 'dark',
            maxLength: 140,
          },
          ...button(96, 1480, 420, 110, 'Learn more', 'light', 36),
        ],
      },
    ],
  },
  {
    key: 'story-photo',
    name: 'Story with photo',
    description: 'A vertical story led by a large photograph, with a short headline underneath.',
    contentType: 'story',
    formatKey: 'ig_story_9x16',
    channels: STORY,
    pages: [
      {
        name: 'Story',
        ground: 'light',
        elements: [
          { kind: 'imageArea', name: 'Image area', box: [54, 250, 972, 900], radius: 24 },
          {
            kind: 'text',
            name: 'Headline',
            role: 'headline',
            text: 'Big moment, short words',
            typeRole: 'display',
            sizePx: 96,
            box: [96, 1190, 888, 240],
            on: 'light',
            maxLength: 50,
          },
          {
            kind: 'text',
            name: 'Body',
            role: 'body',
            text: 'One line of context.',
            typeRole: 'body',
            sizePx: 34,
            box: [96, 1440, 640, 100],
            on: 'light',
            maxLength: 100,
          },
          logo('bottom-right', 180),
        ],
      },
    ],
  },
  {
    key: 'yt-thumbnail',
    name: 'Video thumbnail',
    description: 'A YouTube thumbnail: a big readable title on the left, the picture on the right.',
    contentType: 'thumbnail_banner',
    formatKey: 'yt_thumbnail_1280x720',
    channels: ['youtube'],
    pages: [
      {
        name: 'Thumbnail',
        ground: 'dark',
        elements: [
          { kind: 'imageArea', name: 'Image area', box: [680, 40, 560, 608], radius: 24 },
          {
            kind: 'text',
            name: 'Eyebrow',
            text: 'NEW VIDEO',
            typeRole: 'label',
            sizePx: 28,
            tracking: 0.08,
            box: [72, 64, 500, 40],
            on: 'dark',
            tint: 'accent',
          },
          {
            kind: 'text',
            name: 'Title',
            role: 'headline',
            text: 'How we did it in 30 days',
            typeRole: 'display',
            sizePx: 96,
            lineHeight: 1.05,
            box: [72, 120, 580, 380],
            on: 'dark',
            maxLength: 40,
          },
          logo('bottom-left', 160),
        ],
      },
    ],
  },
  {
    key: 'li-banner',
    name: 'LinkedIn banner',
    description: 'A profile or page banner; the left side stays clear for the profile photo.',
    contentType: 'thumbnail_banner',
    formatKey: 'li_banner_1584x396',
    channels: ['linkedin_page'],
    pages: [
      {
        name: 'Banner',
        ground: 'light',
        elements: [
          {
            kind: 'shape',
            name: 'Accent panel',
            shape: 'rect',
            fill: 'accent',
            box: [0, 0, 360, 396],
            role: 'decoration',
          },
          {
            kind: 'text',
            name: 'Headline',
            role: 'headline',
            text: 'What your company does, in one line',
            typeRole: 'heading',
            sizePx: 56,
            box: [440, 90, 800, 140],
            on: 'light',
            maxLength: 60,
          },
          {
            kind: 'text',
            name: 'Body',
            role: 'body',
            text: 'A short supporting line',
            typeRole: 'body',
            sizePx: 26,
            box: [440, 240, 760, 60],
            on: 'light',
            maxLength: 80,
          },
          logo('bottom-right', 180),
        ],
      },
    ],
  },
  {
    key: 'x-announcement',
    name: 'Landscape announcement',
    description: 'A 16:9 announcement image for X and link posts, on the brand’s dark colour.',
    contentType: 'social_post',
    formatKey: 'x_1600x900',
    channels: ['x', 'linkedin_page', 'facebook_page'],
    pages: [
      {
        name: 'Post',
        ground: 'dark',
        elements: [
          {
            kind: 'text',
            name: 'Eyebrow',
            text: 'ANNOUNCEMENT',
            typeRole: 'label',
            sizePx: 28,
            tracking: 0.08,
            box: [96, 140, 800, 44],
            on: 'dark',
            tint: 'accent',
          },
          {
            kind: 'text',
            name: 'Headline',
            role: 'headline',
            text: 'One line that says what changed',
            typeRole: 'display',
            sizePx: 100,
            lineHeight: 1.05,
            box: [96, 200, 1200, 300],
            on: 'dark',
            maxLength: 60,
          },
          ...button(96, 560, 420, 100, 'Read more', 'light'),
          logo('bottom-right'),
        ],
      },
    ],
  },
  {
    key: 'grid-two-column',
    name: 'Two-column grid',
    description: 'A blank layout grid: a title over two text columns. A starting point for custom artwork.',
    contentType: 'custom',
    formatKey: 'square_1080',
    channels: [],
    pages: [
      {
        name: 'Page 1',
        ground: 'light',
        elements: [
          {
            kind: 'text',
            name: 'Title',
            role: 'headline',
            text: 'Title',
            typeRole: 'heading',
            sizePx: 64,
            box: [96, 96, 888, 170],
            on: 'light',
            maxLength: 60,
          },
          {
            kind: 'shape',
            name: 'Rule',
            shape: 'rect',
            fill: 'accent',
            box: [96, 290, 888, 4],
            role: 'decoration',
          },
          {
            kind: 'text',
            name: 'Column 1',
            role: 'body',
            text: 'Column one text.',
            typeRole: 'body',
            sizePx: 28,
            lineHeight: 1.4,
            box: [96, 330, 420, 500],
            on: 'light',
          },
          {
            kind: 'text',
            name: 'Column 2',
            role: 'body',
            text: 'Column two text.',
            typeRole: 'body',
            sizePx: 28,
            lineHeight: 1.4,
            box: [564, 330, 420, 500],
            on: 'light',
          },
          logo('bottom-right', 180),
        ],
      },
    ],
  },
  {
    key: 'grid-title-body',
    name: 'Title and body grid',
    description: 'A blank 16:9 layout with a title and a text block, for slides, covers and custom artwork.',
    contentType: 'custom',
    formatKey: 'x_1600x900',
    channels: [],
    pages: [
      {
        name: 'Page 1',
        ground: 'light',
        elements: [
          {
            kind: 'text',
            name: 'Title',
            role: 'headline',
            text: 'Title',
            typeRole: 'display',
            sizePx: 88,
            box: [96, 120, 1100, 220],
            on: 'light',
            maxLength: 60,
          },
          {
            kind: 'text',
            name: 'Body',
            role: 'body',
            text: 'Body text.',
            typeRole: 'body',
            sizePx: 34,
            lineHeight: 1.4,
            box: [96, 380, 900, 220],
            on: 'light',
          },
          logo('bottom-right'),
        ],
      },
    ],
  },
];
